package gg.modl.minecraft.core.util;

public final class Permissions {
    private Permissions() {}

    public static final String ADMIN = "modl.admin",
            MOD_ACTIONS = "staff.modactions",
            CHAT_LOGS = "staff.chatlogs",
            COMMAND_LOGS = "staff.commandlogs",
            INTERCEPT = "staff.intercept",
            MAINTENANCE = "staff.maintenance",
            CHAT_TOGGLE = "staff.chat.toggle",
            CHAT_CLEAR = "staff.chat.clear",
            CHAT_SLOW = "staff.chat.slow",
            SETTINGS_VIEW = "admin.settings.view",
            SETTINGS_VIEW_BILLING = "admin.settings.view.billing",
            SETTINGS_MODIFY = "admin.settings.modify",
            SETTINGS_MODIFY_PUNISHMENTS = "admin.settings.modify.punishments",
            SETTINGS_MODIFY_CONTENT = "admin.settings.modify.content",
            SETTINGS_MODIFY_DOMAIN = "admin.settings.modify.domain",
            SETTINGS_MODIFY_BILLING = "admin.settings.modify.billing",
            SETTINGS_MODIFY_MIGRATION = "admin.settings.modify.migration",
            SETTINGS_MODIFY_STORAGE = "admin.settings.modify.storage",
            STAFF_MANAGE = "admin.staff.manage",
            STAFF_MANAGE_MEMBERS = "admin.staff.manage.members",
            STAFF_MANAGE_ROLES = "admin.staff.manage.roles",
            AUDIT_VIEW = "admin.audit.view",
            AUDIT_VIEW_DASHBOARD = "admin.audit.view.dashboard",
            AUDIT_VIEW_ANALYTICS = "admin.audit.view.analytics",
            AUDIT_VIEW_LOGS = "admin.audit.view.logs",
            PUNISHMENT_MODIFY = "punishment.modify",
            PUNISHMENT_MODIFY_PARDON = "punishment.modify.pardon",
            PUNISHMENT_MODIFY_DURATION = "punishment.modify.duration",
            PUNISHMENT_MODIFY_NOTE = "punishment.modify.note",
            PUNISHMENT_MODIFY_EVIDENCE = "punishment.modify.evidence",
            PUNISHMENT_MODIFY_OPTIONS = "punishment.modify.options",
            PUNISHMENT_MODIFY_TICKETS = "punishment.modify.tickets",
            PUNISHMENT_APPLY_MANUAL_BAN = "punishment.apply.manual-ban",
            PUNISHMENT_APPLY_MANUAL_MUTE = "punishment.apply.manual-mute",
            PUNISHMENT_APPLY_KICK = "punishment.apply.kick",
            PUNISHMENT_APPLY_BLACKLIST = "punishment.apply.blacklist",
            TICKET_VIEW_ALL = "ticket.view.all",
            TICKET_VIEW_ALL_NOTES = "ticket.view.all.notes",
            TICKET_REPLY_ALL = "ticket.reply.all",
            TICKET_REPLY_ALL_NOTES = "ticket.reply.all.notes",
            TICKET_CLOSE_ALL = "ticket.close.all",
            TICKET_CLOSE_ALL_LOCK = "ticket.close.all.lock",
            TICKET_MANAGE = "ticket.manage",
            TICKET_MANAGE_TAGS = "ticket.manage.tags",
            TICKET_MANAGE_HIDE = "ticket.manage.hide",
            TICKET_MANAGE_SUBSCRIBE = "ticket.manage.subscribe",
            TICKET_DELETE_ALL = "ticket.delete.all";
}
