package gg.modl.minecraft.api;

import com.google.gson.annotations.SerializedName;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.Nullable;

import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Map;

@Getter @Setter @NoArgsConstructor @AllArgsConstructor
public class Punishment {
    private static final String UNKNOWN = "Unknown", DEFAULT_REASON = "No reason provided",
            STATUS_UNSTARTED = "Unstarted", DATA_KEY_ACTIVE = "active", DATA_KEY_STATUS = "status",
            DATA_KEY_EXPIRES = "expires", DATA_KEY_DURATION = "duration", DATA_KEY_REASON = "reason",
            DATA_KEY_TYPE_NAME = "typeName";

    private @SerializedName("id") String id;
    private @SerializedName("issuerName") String issuerName;
    private @SerializedName("issued") Date issued;
    private @SerializedName("started") Date started;
    private @SerializedName("type") Type type;
    private @SerializedName("typeOrdinal") Integer typeOrdinal;
    private @SerializedName("modifications") List<Modification> modifications;
    private @SerializedName("notes") List<Note> notes;
    private @SerializedName("evidence") List<Evidence> evidence;
    private @SerializedName("attachedTicketIds") List<String> attachedTicketIds;
    private @SerializedName("data") Map<String, Object> dataMap;

    public Map<String, Object> getDataMap() {
        return dataMap != null ? dataMap : Collections.emptyMap();
    }

    public List<Modification> getModifications() {
        return modifications != null ? modifications : Collections.emptyList();
    }

    public List<Note> getNotes() {
        return notes != null ? notes : Collections.emptyList();
    }

    public List<Evidence> getEvidence() {
        return evidence != null ? evidence : Collections.emptyList();
    }

    public int getTypeOrdinal() {
        if (typeOrdinal != null) return typeOrdinal;
        return type != null ? type.getValue() : 0;
    }

    private boolean typeNameContains(String needle) {
        Object tn = getDataMap().get(DATA_KEY_TYPE_NAME);
        return tn instanceof String && ((String) tn).toLowerCase().contains(needle);
    }

    public boolean isBanType() {
        if (PunishmentTypeRegistry.isInitialized()) return PunishmentTypeRegistry.isBan(getTypeOrdinal());
        int o = getTypeOrdinal();
        if (o >= PunishmentTypeRegistry.ORDINAL_BAN && o <= PunishmentTypeRegistry.ORDINAL_BLACKLIST) return true;
        return typeNameContains("ban") || type == Type.BAN || type == Type.SECURITY_BAN
                || type == Type.LINKED_BAN || type == Type.BLACKLIST;
    }

    public boolean isMuteType() {
        if (PunishmentTypeRegistry.isInitialized()) return PunishmentTypeRegistry.isMute(getTypeOrdinal());
        if (getTypeOrdinal() == PunishmentTypeRegistry.ORDINAL_MUTE) return true;
        return typeNameContains("mute") || type == Type.MUTE;
    }

    public boolean isKickType() {
        return PunishmentTypeRegistry.isKick(getTypeOrdinal()) || type == Type.KICK;
    }

    public String getTypeCategory() {
        Object typeName = getDataMap().get(DATA_KEY_TYPE_NAME);
        if (typeName instanceof String && !((String) typeName).isEmpty()) return (String) typeName;

        if (isBanType()) return "Ban";
        if (isMuteType()) return "Mute";
        if (isKickType()) return "Kick";
        return UNKNOWN;
    }

    public String getReason() {
        Object reasonObj = getDataMap().get(DATA_KEY_REASON);
        if (reasonObj instanceof String && !((String) reasonObj).isEmpty()) return (String) reasonObj;

        for (Note note : getNotes()) {
            String text = note.getText();
            if (!isAutoGeneratedNote(text)) return text;
        }
        return DEFAULT_REASON;
    }

    private boolean isAutoGeneratedNote(String noteText) {
        if (noteText == null) return true;
        String lower = noteText.toLowerCase();
        return lower.equals("issued punishment") ||
               lower.startsWith("issued ") ||
               lower.equals("pardoned punishment") ||
               lower.equals("added evidence") ||
               lower.startsWith("changed duration to ") ||
               lower.startsWith("enabled ") ||
               lower.startsWith("disabled ");
    }

    public Date getExpires() {
        Object expires = getDataMap().get(DATA_KEY_EXPIRES);
        if (expires instanceof Date) return (Date) expires;
        if (expires instanceof Number) return new Date(((Number) expires).longValue());
        return null;
    }

    public boolean isActive() {
        if (isKickType()) return false;

        Map<String, Object> map = getDataMap();

        Object activeFlag = map.get(DATA_KEY_ACTIVE);
        if (activeFlag instanceof Boolean && !((Boolean) activeFlag)) return false;

        if (STATUS_UNSTARTED.equals(map.get(DATA_KEY_STATUS))) return false;

        if ((isBanType() || isMuteType()) && started == null) return false;

        if (hasPardonModification()) return false;

        long now = System.currentTimeMillis();
        Date expiry = getExpires();
        if (expiry != null && expiry.getTime() < now) return false;

        if (expiry == null) {
            Date effectiveExpiry = getEffectiveExpiry();
            if (effectiveExpiry != null && effectiveExpiry.getTime() < now) return false;
        }

        return true;
    }

    private static boolean isPardonType(Modification.Type type) {
        return type == Modification.Type.MANUAL_PARDON
                || type == Modification.Type.APPEAL_ACCEPT
                || type == Modification.Type.SYSTEM_PARDON;
    }

    private boolean hasPardonModification() {
        for (Modification mod : getModifications()) {
            if (isPardonType(mod.getType())) return true;
        }
        return false;
    }

    public @Nullable Date getPardonDate() {
        Date pardonDate = null;
        for (Modification mod : getModifications()) {
            if (isPardonType(mod.getType())) pardonDate = mod.getIssued();
        }
        return pardonDate;
    }

    public @Nullable Date getEffectiveExpiry() {
        Long duration = null;
        Date durationBase = null;
        for (Modification mod : getModifications()) {
            if (mod.getEffectiveDuration() != null) {
                duration = mod.getEffectiveDuration();
                durationBase = mod.getIssued();
            }
        }

        if (duration == null) duration = getDuration();
        if (duration == null || duration <= 0) return null;
        if (started == null) return null;
        if (durationBase != null) return new Date(durationBase.getTime() + duration);
        return new Date(started.getTime() + duration);
    }

    @Getter
    public enum Type {
        KICK(0),
        MUTE(1),
        BAN(2),
        SECURITY_BAN(3),
        LINKED_BAN(4),
        BLACKLIST(5);

        private final int value;

        Type(int value) {
            this.value = value;
        }
    }

    public Long getDuration() {
        Object duration = getDataMap().get(DATA_KEY_DURATION);
        if (duration instanceof Number) return ((Number) duration).longValue();
        return null;
    }

    public Long getEffectiveDuration() {
        Long duration = null;
        for (Modification mod : getModifications()) if (mod.getEffectiveDuration() != null) duration = mod.getEffectiveDuration();
        if (duration == null) duration = getDuration();
        return duration;
    }

}
