package gg.modl.minecraft.api;

import com.google.gson.annotations.SerializedName;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.Nullable;

import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Map;

@Getter @Setter @NoArgsConstructor @AllArgsConstructor
public class Punishment {
    private static final String UNKNOWN = "Unknown", DEFAULT_REASON = "No reason provided",
            STATUS_UNSTARTED = "Unstarted", DATA_KEY_ACTIVE = "active", DATA_KEY_STATUS = "status",
            DATA_KEY_EXPIRES = "expires", DATA_KEY_DURATION = "duration", DATA_KEY_REASON = "reason",
            DATA_KEY_TYPE_NAME = "typeName";

    private @SerializedName("id") String id;
    private @SerializedName("issuerName") String issuerName;
    private @SerializedName("issued") Date issued;
    private @SerializedName("started") Date started;
    private @SerializedName("type") Type type;
    private @SerializedName("typeOrdinal") Integer typeOrdinal;
    private @SerializedName("modifications") List<Modification> modifications;
    private @SerializedName("notes") List<Note> notes;
    private @SerializedName("evidence") List<Evidence> evidence;
    private @SerializedName("attachedTicketIds") List<String> attachedTicketIds;
    private @SerializedName("data") Map<String, Object> dataMap;
    private transient PunishmentData data;

    public Map<String, Object> getDataMap() {
        return dataMap != null ? dataMap : Collections.emptyMap();
    }

    public List<Modification> getModifications() {
        return modifications != null ? modifications : Collections.emptyList();
    }

    public List<Note> getNotes() {
        return notes != null ? notes : Collections.emptyList();
    }

    public List<Evidence> getEvidence() {
        return evidence != null ? evidence : Collections.emptyList();
    }

    /**
     * More reliable than getType() for custom punishment types.
     */
    public int getTypeOrdinal() {
        if (typeOrdinal != null) return typeOrdinal;
        return type != null ? type.getValue() : 0;
    }

    public boolean isBanType() {
        return PunishmentTypeRegistry.isBan(getTypeOrdinal());
    }

    public boolean isMuteType() {
        return PunishmentTypeRegistry.isMute(getTypeOrdinal());
    }

    public boolean isKickType() {
        return PunishmentTypeRegistry.isKick(getTypeOrdinal());
    }

    /**
     * Returns display-friendly type category name.
     * Tries dataMap typeName first, then falls back to registry detection.
     */
    public String getTypeCategory() {
        Object typeName = getDataMap().get(DATA_KEY_TYPE_NAME);
        if (typeName instanceof String && !((String) typeName).isEmpty()) return (String) typeName;

        if (isBanType()) return "Ban";
        if (isMuteType()) return "Mute";
        if (isKickType()) return "Kick";
        return UNKNOWN;
    }

    public String getReason() {
        Object reasonObj = getDataMap().get(DATA_KEY_REASON);
        if (reasonObj instanceof String && !((String) reasonObj).isEmpty()) return (String) reasonObj;

        for (Note note : getNotes()) {
            String text = note.getText();
            if (!isAutoGeneratedNote(text)) return text;
        }
        return DEFAULT_REASON;
    }

    private boolean isAutoGeneratedNote(String noteText) {
        if (noteText == null) return true;
        String lower = noteText.toLowerCase();
        return lower.equals("issued punishment") ||
               lower.startsWith("issued ") ||
               lower.equals("pardoned punishment") ||
               lower.equals("added evidence") ||
               lower.startsWith("changed duration to ") ||
               lower.startsWith("enabled ") ||
               lower.startsWith("disabled ");
    }

    public Date getExpires() {
        Object expires = getDataMap().get(DATA_KEY_EXPIRES);
        if (expires instanceof Date) return (Date) expires;
        if (expires instanceof Long) return new Date((Long) expires);
        return null;
    }

    public boolean isActive() {
        if (isKickType()) return false;

        Map<String, Object> map = getDataMap();

        Object activeFlag = map.get(DATA_KEY_ACTIVE);
        if (activeFlag instanceof Boolean && !((Boolean) activeFlag)) return false;

        if (STATUS_UNSTARTED.equals(map.get(DATA_KEY_STATUS))) return false;

        if (hasPardonModification()) return false;

        long now = System.currentTimeMillis();
        Date expiry = getExpires();
        if (expiry != null && expiry.getTime() < now) return false;

        if (expiry == null) {
            Date effectiveExpiry = getEffectiveExpiry();
            if (effectiveExpiry != null && effectiveExpiry.getTime() < now) return false;
        }

        if (isBanType() || isMuteType()) return started != null;

        return true;
    }

    private boolean hasPardonModification() {
        for (Modification mod : getModifications()) {
            Modification.Type modType = mod.getType();
            if (modType == Modification.Type.MANUAL_PARDON ||
                    modType == Modification.Type.APPEAL_ACCEPT ||
                    modType == Modification.Type.SYSTEM_PARDON) {
                return true;
            }
        }
        return false;
    }

    /**
     * Mirrors the backend's getEffectiveExpiry logic, accounting for duration modifications.
     */
    public @Nullable Date getEffectiveExpiry() {
        Long duration = null;
        Date durationBase = null;
        for (Modification mod : getModifications()) {
            if (mod.getEffectiveDuration() != null) {
                duration = mod.getEffectiveDuration();
                durationBase = mod.getIssued();
            }
        }

        if (duration == null) duration = getDuration();
        if (duration == null || duration <= 0) return null;
        if (durationBase != null) return new Date(durationBase.getTime() + duration);
        if (started == null) return null;
        return new Date(started.getTime() + duration);
    }

    @Getter
    public enum Type {
        KICK(0),
        MUTE(1),
        BAN(2),
        SECURITY_BAN(3),
        LINKED_BAN(4),
        BLACKLIST(5);

        private final int value;

        Type(int value) {
            this.value = value;
        }
    }

    public Long getDuration() {
        Object duration = getDataMap().get(DATA_KEY_DURATION);
        if (duration instanceof Number) return ((Number) duration).longValue();
        return null;
    }

    /**
     * Returns the last modification's effectiveDuration, or the original duration if unmodified.
     */
    public Long getEffectiveDuration() {
        Long duration = null;
        for (Modification mod : getModifications()) if (mod.getEffectiveDuration() != null) duration = mod.getEffectiveDuration();
        if (duration == null) duration = getDuration();
        return duration;
    }

}
