package gg.modl.minecraft.core.boot;

import lombok.Data;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.InputStream;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

@Data
public class BootConfig {
    private static final String FILE_NAME = "boot.yml";
    static final String PLACEHOLDER_API_KEY = "your-api-key-here";

    private Mode mode = Mode.STANDALONE;
    private String apiKey = "";
    private String panelUrl = "";
    private boolean testingApi = false;
    private String proxyType;
    private int bridgePort = 25590;

    // Transient fields set by setup wizard for bridge-only mode — not serialized to boot.yml
    private transient String wizardProxyHost;
    private transient int wizardProxyPort = 25590;

    public enum Mode {
        STANDALONE,
        BRIDGE_ONLY,
        PROXY;

        public static Mode fromString(String value) {
            if (value == null) return STANDALONE;
            String normalized = value.toLowerCase().replace("_", "-");
            if ("bridge-only".equals(normalized)) return BRIDGE_ONLY;
            if ("proxy".equals(normalized)) return PROXY;
            return STANDALONE;
        }

        public String toYaml() {
            if (this == STANDALONE) return "standalone";
            if (this == BRIDGE_ONLY) return "bridge-only";
            return "proxy";
        }
    }

    public boolean isValid() {
        if (apiKey == null || apiKey.isEmpty() || apiKey.equals(PLACEHOLDER_API_KEY)) {
            return mode == Mode.BRIDGE_ONLY; // bridge-only can work without API key for now
        }
        if (mode != Mode.BRIDGE_ONLY && (panelUrl == null || panelUrl.isEmpty())) {
            return false;
        }
        return true;
    }

    public static boolean exists(Path dataDir) {
        return Files.exists(dataDir.resolve(FILE_NAME));
    }

    @SuppressWarnings("unchecked")
    public static BootConfig load(Path dataDir) throws IOException {
        Path file = dataDir.resolve(FILE_NAME);
        if (!Files.exists(file)) return null;

        Yaml yaml = new Yaml();
        try (InputStream is = Files.newInputStream(file)) {
            Map<String, Object> data = yaml.load(is);
            if (data == null) return null;
            return fromMap(data);
        }
    }

    public void save(Path dataDir) throws IOException {
        Path file = dataDir.resolve(FILE_NAME);
        if (!Files.exists(dataDir)) Files.createDirectories(dataDir);

        DumperOptions options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setPrettyFlow(true);
        options.setDefaultScalarStyle(DumperOptions.ScalarStyle.PLAIN);

        Yaml yaml = new Yaml(options);
        Map<String, Object> map = toMap();

        try (Writer writer = Files.newBufferedWriter(file)) {
            writer.write("# Auto-generated by setup wizard. Delete to re-run wizard.\n");
            yaml.dump(map, writer);
        }
    }

    @SuppressWarnings("unchecked")
    private static BootConfig fromMap(Map<String, Object> data) {
        BootConfig config = new BootConfig();
        config.setMode(Mode.fromString((String) data.get("mode")));
        config.setApiKey(getStr(data, "api-key", ""));
        config.setPanelUrl(getStr(data, "panel-url", ""));
        config.setTestingApi(getBool(data, "testing-api", false));
        config.setProxyType(getStr(data, "proxy-type", null));
        config.setBridgePort(getInt(data, "bridge-port", 25590));

        return config;
    }

    private Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("mode", mode.toYaml());
        map.put("api-key", apiKey);
        map.put("panel-url", panelUrl);
        map.put("testing-api", testingApi);
        if (proxyType != null) map.put("proxy-type", proxyType);
        if (mode == Mode.PROXY) map.put("bridge-port", bridgePort);

        return map;
    }

    public static void saveTemplate(Path dataDir) throws IOException {
        Path file = dataDir.resolve(FILE_NAME);
        if (!Files.exists(dataDir)) Files.createDirectories(dataDir);
        try (Writer writer = Files.newBufferedWriter(file)) {
            writer.write("# modl.gg Boot Configuration\n");
            writer.write("# Edit this file and restart the server.\n");
            writer.write("# To register a new server, visit https://modl.gg/register\n");
            writer.write("#\n");
            writer.write("# mode: standalone | bridge-only | proxy\n");
            writer.write("mode: proxy\n");
            writer.write("\n");
            writer.write("# Your API key from the modl.gg panel\n");
            writer.write("api-key: \"" + PLACEHOLDER_API_KEY + "\"\n");
            writer.write("\n");
            writer.write("# Your panel URL (e.g. https://myserver.modl.gg)\n");
            writer.write("panel-url: \"https://yourserver.modl.gg\"\n");
            writer.write("\n");
            writer.write("# Uncomment to use the testing API (api.modl.top)\n");
            writer.write("# testing-api: true\n");
            writer.write("\n");
            writer.write("# Bridge listen port (proxy mode only — backends connect to this port)\n");
            writer.write("# bridge-port: 25590\n");
        }
    }

    private static String getStr(Map<String, Object> map, String key, String def) {
        Object val = map.get(key);
        return val instanceof String ? (String) val : def;
    }

    private static int getInt(Map<String, Object> map, String key, int def) {
        Object val = map.get(key);
        return val instanceof Number ? ((Number) val).intValue() : def;
    }

    private static boolean getBool(Map<String, Object> map, String key, boolean def) {
        Object val = map.get(key);
        return val instanceof Boolean ? (Boolean) val : def;
    }
}
