package gg.modl.minecraft.core.boot;

import lombok.Data;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.InputStream;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

@Data
public class BootConfig {
    private static final String FILE_NAME = "boot.yml";

    private Mode mode = Mode.STANDALONE;
    private String apiKey = "";
    private String panelUrl = "";
    private List<BackendBridge> backendBridges = new ArrayList<>();

    public enum Mode {
        STANDALONE,
        BRIDGE_ONLY,
        PROXY;

        public static Mode fromString(String value) {
            if (value == null) return STANDALONE;
            return switch (value.toLowerCase().replace("_", "-")) {
                case "bridge-only", "bridge_only" -> BRIDGE_ONLY;
                case "proxy" -> PROXY;
                default -> STANDALONE;
            };
        }

        public String toYaml() {
            return switch (this) {
                case STANDALONE -> "standalone";
                case BRIDGE_ONLY -> "bridge-only";
                case PROXY -> "proxy";
            };
        }
    }

    @Data
    public static class BackendBridge {
        private String host = "127.0.0.1";
        private int port = 25590;

        public BackendBridge() {}

        public BackendBridge(String host, int port) {
            this.host = host;
            this.port = port;
        }
    }

    public boolean isValid() {
        if (apiKey == null || apiKey.isEmpty() || apiKey.equals("your-api-key-here")) {
            return mode == Mode.BRIDGE_ONLY; // bridge-only can work without API key for now
        }
        if (mode != Mode.BRIDGE_ONLY && (panelUrl == null || panelUrl.isEmpty())) {
            return false;
        }
        return true;
    }

    public static boolean exists(Path dataDir) {
        return Files.exists(dataDir.resolve(FILE_NAME));
    }

    @SuppressWarnings("unchecked")
    public static BootConfig load(Path dataDir) throws IOException {
        Path file = dataDir.resolve(FILE_NAME);
        if (!Files.exists(file)) return null;

        Yaml yaml = new Yaml();
        try (InputStream is = Files.newInputStream(file)) {
            Map<String, Object> data = yaml.load(is);
            if (data == null) return null;
            return fromMap(data);
        }
    }

    public void save(Path dataDir) throws IOException {
        Path file = dataDir.resolve(FILE_NAME);
        if (!Files.exists(dataDir)) Files.createDirectories(dataDir);

        DumperOptions options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setPrettyFlow(true);
        options.setDefaultScalarStyle(DumperOptions.ScalarStyle.PLAIN);

        Yaml yaml = new Yaml(options);
        Map<String, Object> map = toMap();

        try (Writer writer = Files.newBufferedWriter(file)) {
            writer.write("# Auto-generated by setup wizard. Delete to re-run wizard.\n");
            yaml.dump(map, writer);
        }
    }

    @SuppressWarnings("unchecked")
    private static BootConfig fromMap(Map<String, Object> data) {
        BootConfig config = new BootConfig();
        config.setMode(Mode.fromString((String) data.get("mode")));
        config.setApiKey(getStr(data, "api-key", ""));
        config.setPanelUrl(getStr(data, "panel-url", ""));

        Object backendsObj = data.get("backend-bridges");
        if (backendsObj instanceof List<?> list) {
            List<BackendBridge> bridges = new ArrayList<>();
            for (Object item : list) {
                if (item instanceof Map<?, ?> itemMap) {
                    BackendBridge bb = new BackendBridge();
                    bb.setHost(getStr((Map<String, Object>) itemMap, "host", "127.0.0.1"));
                    bb.setPort(getInt((Map<String, Object>) itemMap, "port", 25590));
                    bridges.add(bb);
                }
            }
            config.setBackendBridges(bridges);
        }

        return config;
    }

    private Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("mode", mode.toYaml());
        map.put("api-key", apiKey);
        map.put("panel-url", panelUrl);

        if (mode == Mode.PROXY && !backendBridges.isEmpty()) {
            List<Map<String, Object>> backends = new ArrayList<>();
            for (BackendBridge bb : backendBridges) {
                Map<String, Object> bbMap = new LinkedHashMap<>();
                bbMap.put("host", bb.getHost());
                bbMap.put("port", bb.getPort());
                backends.add(bbMap);
            }
            map.put("backend-bridges", backends);
        }

        return map;
    }

    private static String getStr(Map<String, Object> map, String key, String def) {
        Object val = map.get(key);
        return val instanceof String s ? s : def;
    }

    private static int getInt(Map<String, Object> map, String key, int def) {
        Object val = map.get(key);
        return val instanceof Number n ? n.intValue() : def;
    }

    private static boolean getBool(Map<String, Object> map, String key, boolean def) {
        Object val = map.get(key);
        return val instanceof Boolean b ? b : def;
    }
}
